-- 创建文档表
CREATE TABLE documents (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(500) NOT NULL COMMENT '文档标题',
    original_filename VARCHAR(255) NOT NULL COMMENT '原始文件名',
    file_type VARCHAR(10) COMMENT '文件类型',
    content LONGTEXT COMMENT '文档内容',
    summary VARCHAR(1000) COMMENT '文档摘要',
    category VARCHAR(100) COMMENT '文档分类',
    keywords VARCHAR(500) COMMENT '关键词',
    file_size BIGINT COMMENT '文件大小',
    file_url VARCHAR(500) COMMENT 'OSS文件URL',
    status VARCHAR(20) DEFAULT 'ACTIVE' COMMENT '文档状态',
    is_public BOOLEAN DEFAULT FALSE COMMENT '是否公开',
    download_count INT DEFAULT 0 COMMENT '下载次数',
    view_count INT DEFAULT 0 COMMENT '查看次数',
    uploader_id BIGINT COMMENT '上传者ID',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    version INT DEFAULT 1 COMMENT '版本号',
    parent_id BIGINT COMMENT '父文档ID',
    language VARCHAR(10) DEFAULT 'zh-CN' COMMENT '文档语言',
    
    INDEX idx_title (title),
    INDEX idx_category (category),
    INDEX idx_status (status),
    INDEX idx_uploader_id (uploader_id),
    INDEX idx_created_at (created_at),
    INDEX idx_is_public (is_public),
    INDEX idx_file_type (file_type),
    FULLTEXT KEY ft_content (content),
    FULLTEXT KEY ft_keywords (keywords),
    FULLTEXT KEY ft_title_content (title, content)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='知识文档表'; 