# 数据库配置文件
# 注意：实际使用时应使用环境变量或配置管理工具来管理敏感信息

development:
  driver: mysql
  host: localhost
  port: 3306
  database: sihui_dev
  username: sihui_user
  password: ${DB_PASSWORD}
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
  pool:
    min: 5
    max: 20
    timeout: 30000

test:
  driver: mysql
  host: localhost
  port: 3306
  database: sihui_test
  username: sihui_test_user
  password: ${DB_TEST_PASSWORD}
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
  pool:
    min: 2
    max: 10
    timeout: 30000

production:
  driver: mysql
  host: ${DB_HOST}
  port: ${DB_PORT}
  database: ${DB_NAME}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
  pool:
    min: 10
    max: 50
    timeout: 30000
  ssl:
    enabled: true
    verify: true 